#!/usr/bin/env python

Import('env')
Import('env_modules')

env_luascript = env_modules.Clone()

lib_include_path = './lib'

if not env.msvc:
    env_luascript.Append(CXXFLAGS=['-O0', '-std=c++17'])
else:
    env_luascript.Append(CXXFLAGS=['/std:c++17'])

env_luascript.Append(CPPPATH=lib_include_path)

env_luascript.add_source_files(env.modules_sources,'*.cpp')

SConscript('lib/lua/SCsub')

if env['tools']:
	env_luascript.add_source_files(env.modules_sources, './editor/*.cpp')

Export('env')
