#!/usr/bin/env python

Import('env')
Import('env_modules')

env_cloned = env_modules.Clone()

if not env.msvc:
    env_cloned.Append(CXXFLAGS=['-O0', '-std=c++17'])
else:
    env_cloned.Append(CXXFLAGS=['/std:c++17'])

SConscript('lib/lua/SCsub')
SConscript('lib/antlr4/SCsub')
SConscript('parser/SCsub')

if env['tools']:
    SConscript('editor/SCsub')

env_cloned.add_source_files(env.modules_sources,'*.cpp')

Export('env')
