#!/usr/bin/env python

Import('env')
Import('env_modules')

env_lpeg = env_modules.Clone()

lua_include_path = '../lua'

env_lpeg.Append(CFLAGS=['-O2', '-std=c99'])
env_lpeg.Append(CPPPATH=lua_include_path)

env_lpeg.add_source_files(env.modules_sources,'*.c')

Export('env')
