#!/usr/bin/env python

Import('env')
Import('env_modules')

env_cloned = env_modules.Clone()

lib_include_path = '.'

env_cloned.Append(CPPPATH=lib_include_path)

env_cloned.add_source_files(env.modules_sources,'*.cpp')

Export('env')
