#!/usr/bin/env python

Import('env')
Import('env_luascript')

env_antlr4 = env_luascript.Clone()

env_antlr4.Append(CPPPATH=['.'])

# Enable exceptions for ANTLR4
if env_antlr4.msvc:
    env_antlr4.Append(CPPDEFINES=[("_HAS_EXCEPTIONS", 1)])
else:
    env_antlr4.Append(CCFLAGS=["-fexceptions"])

env_antlr4.add_source_files(env.modules_sources,'*.cpp')
env_antlr4.add_source_files(env.modules_sources,'atn/*.cpp')
env_antlr4.add_source_files(env.modules_sources,'dfa/*.cpp')
env_antlr4.add_source_files(env.modules_sources,'internal/*.cpp')
env_antlr4.add_source_files(env.modules_sources,'misc/*.cpp')
env_antlr4.add_source_files(env.modules_sources,'support/*.cpp')
env_antlr4.add_source_files(env.modules_sources,'tree/*.cpp')
env_antlr4.add_source_files(env.modules_sources,'tree/pattern/*.cpp')
env_antlr4.add_source_files(env.modules_sources,'tree/xpath/*.cpp')
