#!/usr/bin/env python

Import('env')
Import('env_luascript')

env_lua = env_luascript.Clone()

if env_lua['PLATFORM'] == 'posix':
    env_lua.Append(CPPDEFINES='LUA_USE_POSIX')

if not env.msvc:
    env_lua['CFLAGS'].remove('-std=gnu11')
    env_lua.Append(CFLAGS=['-std=c99'])

env_lua.add_source_files(env.modules_sources,'*.c')
