#!/usr/bin/env python

Import('env')
# Import('env_modules')

env_cloned = env.Clone()

env_cloned.Append(CPPPATH = ['../lib/antlr4'])

env_cloned.add_source_files(env.modules_sources,'generated/*.cpp')
env_cloned.add_source_files(env.modules_sources,'*.cpp')

Export('env')
